---
title: "vap_lca_tbls_no_w_il10"
author: "Ted Liu"
date: "2025-02-28"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
library(dplyr)
library(tidyLPA)
library(factoextra)
library(mice)
library(openxlsx)
library(ggplot2)
library(purrr)
library(mclust)
library(cluster)
library(missForest)
library(furrr)
library(parallel)
library(progressr)
library(umap)
library(arsenal)
library(table1)
library(sandwich)
library(stringr)
library(ComplexHeatmap)
source("helper_functions.R")
```


```{r preprocess}
set.seed(1)
df <- read.csv("./data/Daily_merged_2025-02-27.csv")
df <- df %>% 
  filter(repeat. == 1) %>%
  filter(!is.na(balf_PD.L1_V1_imputed)) 
vap_df <- df %>% filter(cohort == "vap")

vap_balf_biomarkers <- c("Amphiregulin", "Calprotectin", "CD163", "G.CSF", "GM.CSF", "IL.12.IL.23p40",
                         "IL.15", "IL.16", "IL.17A", "IL.1α", "IL.1β_proinf", "IL.6_proinf", "IL.7",
                         #"IL-8_chemo",
                         "IL.8_proinf", "IL.10_proinf", 
                         "IP.10_chemo", "MCP.1_chemo", "MCP.4_chemo",
                         "MIP.1α_chemo", "MIP.1β_chemo", "PD.L1", "sRAGE", "TARC_chemo", "TNF.RI", "TNF.α_proinf", "VEGF")


vap_balf_biomarkers <- paste0("balf_", vap_balf_biomarkers, "_V1_imputed")

vap_biomarkers <- vap_balf_biomarkers
vap_df <- vap_df %>%
  mutate(across(all_of(vap_biomarkers), ~ ifelse(is.na(.), median(., na.rm = TRUE), .)))

vap_df[, vap_biomarkers] <- scale(log2(vap_df[, vap_biomarkers] + 1))

vap_biomarkers_plus_id <- append(
  vap_biomarkers, "subject_id"
)


vap_curr <- vap_df %>%
  select(all_of(vap_biomarkers_plus_id)) %>%
  filter(if_any(vap_biomarkers, ~ !is.na(.)))  # remove subject ids who have all null

vap_curr <- vap_curr %>%
  mutate(subject_id = as.numeric(subject_id))

# Remove columns that have more than 20% missing
vap_curr <- vap_curr[, which(colMeans(!is.na(vap_curr)) > 0.2)]

#write.csv(vap_curr, file="vap_biomarkers_w_il10.csv")

# Factorize outcomes for tbl1
vap_df$Sex <- factor(vap_df$Sex)
vap_df$X28d_mortality <- factor(vap_df$X28d_mortality)
vap_df$colony_10000_yes1_no0 <- factor(vap_df$colony_10000_yes1_no0)
vap_df$colony_1000_yes1_no0 <- factor(vap_df$colony_1000_yes1_no0)
vap_df$apache_iii_admit <- as.numeric(vap_df$apache_iii_admit)
vap_df$ARDS_final_1yes_0no <- factor(vap_df$ARDS_final_1yes_0no)
vap_df$hospital_mortality <- factor(vap_df$hospital_mortality)
vap_df$icu_mortality <- factor(vap_df$icu_mortality)
vap_df$any_pressors_during_admission <- factor(vap_df$any_pressors_during_admission)
vap_df$any_abx_during_admission <- factor(vap_df$any_abx_during_admission)
vap_df$bronch_ecmo_0 <- factor(vap_df$bronch_ecmo_0)

```

# MClust Results

```{r mclust, eval=T}
vap_bic <- mclustBIC(vap_curr %>% select(-subject_id))
plot(vap_bic)
summary(vap_bic)

vap_icl <- mclustICL(vap_curr %>% select(-subject_id))
plot(vap_icl)
summary(vap_icl)

#LRT <- mclustBootstrapLRT(vap_curr %>% select(-subject_id), modelName = "VVE")
#LRT
```

```{r mclust_bestmodel}
# Assign the clusters to the dataframe
best_model <- Mclust(vap_curr %>% select(-subject_id), G = 4, modelNames = "VVE")

vap_curr$cluster <- best_model$classification
vap_curr <- vap_curr %>%
  mutate(subject_id = as.character(subject_id))

vap_df_cluster <- vap_df %>%
  left_join(vap_curr %>% select(subject_id, cluster), by = "subject_id")
```

```{r mclust_heatmap}
vap_curr_ordered <- vap_curr %>% arrange(cluster)

biomarker_matrix <- as.matrix(vap_curr_ordered %>% select(-subject_id, -cluster))

rownames(biomarker_matrix) <- vap_curr_ordered$subject_id


row_ann <- rowAnnotation(
  Cluster = factor(vap_curr_ordered$cluster),
  col = list(Cluster = c("1" = "#E41A1C", "2" = "#377EB8",
                         "3" = "#4DAF4A", "4" = "#984EA3"))
)

# Generate the heatmap
heatmap_obj <- Heatmap(
  biomarker_matrix,
  name = "Expression",          # Legend title
  show_row_names = FALSE,       # Hide subject names to reduce clutter
  show_column_names = TRUE,     # Display biomarker names
  cluster_rows = FALSE,         # Keep the order based on clusters
  cluster_columns = TRUE,       # Optionally cluster biomarkers
  left_annotation = row_ann,    # Attach cluster annotation to rows
  heatmap_legend_param = list(title = "Expression")
)

png(filename = "mclust_w_il10_heatmap.png", width = 800, height = 600)
draw(heatmap_obj, newpage = TRUE)
dev.off()

```


```{r mclust_umap}
set.seed(1)
umap_res <- umap(vap_df_cluster %>% select(all_of(vap_biomarkers)))
# Create a data frame from the UMAP layout and add the cluster assignments
umap_data <- data.frame(UMAP1 = umap_res$layout[, 1],
                        UMAP2 = umap_res$layout[, 2],
                        cluster = as.factor(vap_df_cluster$cluster))

# Plot the UMAP results colored by cluster
p <- ggplot(umap_data, aes(x = UMAP1, y = UMAP2, color = cluster)) +
  geom_point(size = 1) +
  theme_minimal() +
  labs(title = "UMAP Plot of Clusters",
       x = "UMAP Dimension 1",
       y = "UMAP Dimension 2")
ggsave(filename = "umap_mclust_w_il10.png")
```


```{r mclust_pca}
set.seed(1)
pca_res <- prcomp(vap_df_cluster %>% select(all_of(vap_biomarkers)), center = FALSE, scale. = FALSE)
# Combine PCA results with the cluster information
pca_data <- data.frame(pca_res$x, cluster = as.factor(vap_df_cluster$cluster))

# Plot the first two principal components colored by cluster
p <- ggplot(pca_data, aes(x = PC1, y = PC2, color = cluster)) +
  geom_point(size = 1) +
  theme_minimal() +
  labs(title = "PCA Plot of Clusters",
       x = "Principal Component 1",
       y = "Principal Component 2")

ggsave(filename = "pca_mclust_w_il10.png")

```



```{r mclust_tbl1, results='asis', eval=T}

vap_df_cluster <- vap_df_cluster %>%
  mutate(Race = trimws(sub(",.*", "", Race))) %>%
  mutate(Race = gsub("Black or African-American", "Black or African American", Race)) %>%
  mutate(Race = gsub("^Alaska Native.*", "American Indian or Native Alaskan", Race)) %>%
  mutate(Race = gsub("^American Indian.*", "American Indian or Native Alaskan", Race)) %>%
  mutate(Race = gsub("^Pacific Islander.*", "Native Hawaiian or Pacific Islander", Race)) %>%
  mutate(Race = gsub("Unable to Collect", "Unavailable or Unknown", Race))

#vap_df_cluster %>% distinct(primary_organism_b1_datetime)
desired_levels <- c("cineto1", "bahstrep2", "candida3", "citrobacter4", "oralflora5",
                    "coryneanddipther6", "enterbacter7", "ecoli8", "hinflu9",
                    "klebs10", "neisseria11", "pseudomonas12", "serratia13",
                    "staph14", "spneumo15", "yeast16", "multiple17", "other18",
                    "nothing19")

vap_df_cluster <- vap_df_cluster %>%
  mutate(mapped_organism = sapply(primary_organism_b1_datetime, map_category)) %>%
  mutate(mapped_organism = factor(mapped_organism, levels = desired_levels)) %>%
  arrange(mapped_organism)

tbl1 <- tableby(
  cluster ~ Age + Sex + BMI + Race + 
    + icu_admit_type + bronch_day_1 + bronch_day_1_indexed_to_intubation + X28d_mortality + colony_1000_yes1_no0
    + colony_10000_yes1_no0 + perc_neutrophils_bal_b1 + bal_nucleated_cells_b1 + X28d_mortality + hospital_mortality + icu_mortality
    + apache_iii_admit + sofa_icu + sofa_b1 + bronch_ecmo_0 + bronch_pf_8am_calculated_0 + bronch_sf_8am_calculated_0 + bronch_oi_8am_calculated_0 
    + vfds_admit + vfds_bronch + vfds_first_intubtation + mapped_organism, 
  data=vap_df_cluster, control = tableby.control(numeric.stats = c("median", "q1q3"), test = FALSE))
print(summary(tbl1, text = T))

```